name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ARCH_IMAGE: archlinux:base

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build + Test (Arch Linux)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            "$ARCH_IMAGE" \
            bash -lc '
              set -euxo pipefail
              pacman -Syu --noconfirm
              # Base toolchain and essentials
              pkgs=(
                git curl python
                base-devel zip unzip tar
                clang cmake ninja pkgconf lld
                glslang shaderc spirv-tools
                vulkan-headers vulkan-icd-loader vulkan-validation-layers
                # SDL windowing backends (X11/Wayland) for Linux builds
                libx11 xorgproto libxext libxcb libxkbcommon wayland wayland-protocols
              )
              pacman -S --noconfirm --needed "${pkgs[@]}"

              # Provide VulkanMemoryAllocator via vcpkg (Arch package not available/providing CMake config)
              git clone --depth 1 https://github.com/microsoft/vcpkg /opt/vcpkg
              /opt/vcpkg/bootstrap-vcpkg.sh -disableMetrics
              export VCPKG_ROOT=/opt/vcpkg
              /opt/vcpkg/vcpkg install vulkan-memory-allocator

              # Install uv (Python packaging/runner)
              curl -LsSf https://astral.sh/uv/install.sh | sh
              export PATH="$HOME/.local/bin:$PATH"

              uv --version
              uv run python --version

              export V_LOG_LEVEL=info
              # Debug build + tests
              uv run v.py test
              # Release build + tests
              uv run v.py build --release
              uv run v.py test --release
            '
