name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build + Test (Arch Linux)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            archlinux:latest \
            bash -lc '
              set -euxo pipefail
              pacman -Syu --noconfirm
              # Base toolchain and essentials
              pacman -S --noconfirm --needed \
                git curl python \
                clang cmake ninja pkgconf lld \
                glslang shaderc spirv-tools \
                vulkan-headers vulkan-icd-loader vulkan-validation-layers \
                # SDL windowing backends (X11/Wayland) for Linux builds
                libx11 xorgproto libxext libxcb libxkbcommon wayland wayland-protocols

              # Install uv (Python packaging/runner)
              curl -LsSf https://astral.sh/uv/install.sh | sh
              export PATH="$HOME/.local/bin:$PATH"

              uv --version
              uv run python --version

              export V_LOG_LEVEL=info
              # Debug build + tests
              uv run v.py test
              # Release build + tests
              uv run v.py build --release
              uv run v.py test --release
            '
