name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools
        run: |
          sudo apt-get update
          # Base toolchain
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libvulkan-dev
          # Vulkan utility libraries (replaces vulkan-validationlayers-dev on newer Ubuntu)
          sudo apt-get install -y vulkan-utility-libraries-dev || \
            sudo apt-get install -y vulkan-validationlayers-dev
          # Shaderc tools provide `glslc` (name varies across Ubuntu versions)
          sudo apt-get install -y shaderc-tools || sudo apt-get install -y shaderc
          # Headers for shaderc (safe to always install)
          sudo apt-get install -y libshaderc-dev
          # glslang dev libraries are required by daxa's pipeline manager
          sudo apt-get install -y glslang-dev
          # VMA package name may be unavailable on newer images; it's pulled by the
          # utility meta package above. Try to install but ignore if missing.
          sudo apt-get install -y vulkan-memory-allocator-dev || true

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Build + Test (Debug)
        env:
          # Keep test logs concise by default; v.py --verbose 
          # switches to V_LOG_LEVEL=trace automatically.
          V_LOG_LEVEL: info
        run: |
          uv --version
          uv run python --version
          uv run v.py test

      - name: Build + Test (Release)
        env:
          V_LOG_LEVEL: info
        run: |
          uv run v.py build --release
          uv run v.py test --release
